//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyThuVien.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class QUYDINH
    {
        public int MaQD { get; set; }
        public string TenQD { get; set; }
        public string GiaTri { get; set; }
        public string TinhTrang { get; set; }
        public int Xoa { get; set; }
    }
}
